const  GET_POST_SUCCESS = 'GET_POST_SUCCESS';
const  COMMENTS = 'COMMENTS';
const  OPEN_COMMENT = 'OPEN_COMMENT';
const  USER_INFO = 'USER_INFO';
const  OPEN_USER_INFO = 'OPEN_USER_INFO';

export {
    GET_POST_SUCCESS,
    COMMENTS,
    OPEN_COMMENT,
    USER_INFO,
    OPEN_USER_INFO
}